<!doctype html>
<html>
<head>
	<title>Live Chat</title>
	<link rel="stylesheet" href="stylesheet.css">
	<script src="script.js"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body class="container">
	<h1>Sokoban!!!!</h1>
	<div id="data">
	</div>
</body>
</html>